theme: jekyll-theme-cayman
title: Joint Modeling in Deep Recommender Systems
email: jia.pengyue@my.cityu.edu.hk
description: >- # this means to ignore newlines until "baseurl:"
 Fundamentals and Advances
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Jia-py
